webtalk_init -webtalk_dir /home/mike/Documents/osiris-hdl/projects/zybo_dvi_output/zybo_dvi_output.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jan 14 14:04:29 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d730e8dad0dc5026b9736e7bf7837f0b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3a53e749-15f4-45e0-8b61-2ebce3e9085a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "elementary OS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "elementary OS Freya" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2001.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "elementary OS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "elementary OS Freya" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "800.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key chain -value "0000400013722093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "01:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/Zybo/15000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/Zybo/15000000:Digilent/Zybo/15000000:" -context "labtool\\usage"
webtalk_transmit -clientid 943531311 -regid "" -xml /home/mike/Documents/osiris-hdl/projects/zybo_dvi_output/zybo_dvi_output.hw/webtalk/usage_statistics_ext_labtool.xml -html /home/mike/Documents/osiris-hdl/projects/zybo_dvi_output/zybo_dvi_output.hw/webtalk/usage_statistics_ext_labtool.html -wdm /home/mike/Documents/osiris-hdl/projects/zybo_dvi_output/zybo_dvi_output.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
