language: python
python:
    - "2.7"
sudo: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y iverilog
install:
    #- pip install .
    - pip install -r requirements.txt
script: make test