# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/ZYBO_Master.xdc

# Block Designs: bd/linebuffer_test/linebuffer_test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test || ORIG_REF_NAME==linebuffer_test}]

# IP: bd/linebuffer_test/ip/linebuffer_test_processing_system7_0_0/linebuffer_test_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_processing_system7_0_0 || ORIG_REF_NAME==linebuffer_test_processing_system7_0_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_o_buf_controller_0_0/linebuffer_test_o_buf_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_o_buf_controller_0_0 || ORIG_REF_NAME==linebuffer_test_o_buf_controller_0_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_processing_system7_0_axi_periph_0/linebuffer_test_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==linebuffer_test_processing_system7_0_axi_periph_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_rst_processing_system7_0_100M_0/linebuffer_test_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==linebuffer_test_rst_processing_system7_0_100M_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_axi_mem_intercon_0/linebuffer_test_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_axi_mem_intercon_0 || ORIG_REF_NAME==linebuffer_test_axi_mem_intercon_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_blk_mem_gen_0_1/linebuffer_test_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_blk_mem_gen_0_1 || ORIG_REF_NAME==linebuffer_test_blk_mem_gen_0_1}]

# IP: bd/linebuffer_test/ip/linebuffer_test_axi_bram_ctrl_0_1/linebuffer_test_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_axi_bram_ctrl_0_1 || ORIG_REF_NAME==linebuffer_test_axi_bram_ctrl_0_1}]

# IP: bd/linebuffer_test/ip/linebuffer_test_axi_cdma_0_1/linebuffer_test_axi_cdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_axi_cdma_0_1 || ORIG_REF_NAME==linebuffer_test_axi_cdma_0_1}]

# IP: bd/linebuffer_test/ip/linebuffer_test_axi_mem_intercon_1_0/linebuffer_test_axi_mem_intercon_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_axi_mem_intercon_1_0 || ORIG_REF_NAME==linebuffer_test_axi_mem_intercon_1_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_xbar_0/linebuffer_test_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_xbar_0 || ORIG_REF_NAME==linebuffer_test_xbar_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_clk_wiz_0_0/linebuffer_test_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_clk_wiz_0_0 || ORIG_REF_NAME==linebuffer_test_clk_wiz_0_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_xbar_1/linebuffer_test_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_xbar_1 || ORIG_REF_NAME==linebuffer_test_xbar_1}]

# IP: bd/linebuffer_test/ip/linebuffer_test_xbar_2/linebuffer_test_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_xbar_2 || ORIG_REF_NAME==linebuffer_test_xbar_2}]

# IP: bd/linebuffer_test/ip/linebuffer_test_xlconstant_0_1/linebuffer_test_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_xlconstant_0_1 || ORIG_REF_NAME==linebuffer_test_xlconstant_0_1}]

# IP: bd/linebuffer_test/ip/linebuffer_test_blk_mem_gen_0_0/linebuffer_test_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_blk_mem_gen_0_0 || ORIG_REF_NAME==linebuffer_test_blk_mem_gen_0_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_axi_cdma_0_0/linebuffer_test_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_axi_cdma_0_0 || ORIG_REF_NAME==linebuffer_test_axi_cdma_0_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_axi_bram_ctrl_0_0/linebuffer_test_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_axi_bram_ctrl_0_0 || ORIG_REF_NAME==linebuffer_test_axi_bram_ctrl_0_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_i_buf_controller_0_0/linebuffer_test_i_buf_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_i_buf_controller_0_0 || ORIG_REF_NAME==linebuffer_test_i_buf_controller_0_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_xlconcat_0_0/linebuffer_test_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_xlconcat_0_0 || ORIG_REF_NAME==linebuffer_test_xlconcat_0_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_xlconcat_0_1/linebuffer_test_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_xlconcat_0_1 || ORIG_REF_NAME==linebuffer_test_xlconcat_0_1}]

# IP: bd/linebuffer_test/ip/linebuffer_test_rgb2dvi_0_0/linebuffer_test_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_rgb2dvi_0_0 || ORIG_REF_NAME==linebuffer_test_rgb2dvi_0_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_clk_wiz_0_1/linebuffer_test_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_clk_wiz_0_1 || ORIG_REF_NAME==linebuffer_test_clk_wiz_0_1}]

# IP: bd/linebuffer_test/ip/linebuffer_test_ov7670_capture_0_0/linebuffer_test_ov7670_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_ov7670_capture_0_0 || ORIG_REF_NAME==linebuffer_test_ov7670_capture_0_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_ov7670_controller_0_0/linebuffer_test_ov7670_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_ov7670_controller_0_0 || ORIG_REF_NAME==linebuffer_test_ov7670_controller_0_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_util_vector_logic_0_0/linebuffer_test_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_util_vector_logic_0_0 || ORIG_REF_NAME==linebuffer_test_util_vector_logic_0_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_xlconcat_0_2/linebuffer_test_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_xlconcat_0_2 || ORIG_REF_NAME==linebuffer_test_xlconcat_0_2}]

# IP: bd/linebuffer_test/ip/linebuffer_test_xlconstant_0_0/linebuffer_test_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_xlconstant_0_0 || ORIG_REF_NAME==linebuffer_test_xlconstant_0_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_util_vector_logic_0_1/linebuffer_test_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_util_vector_logic_0_1 || ORIG_REF_NAME==linebuffer_test_util_vector_logic_0_1}]

# IP: bd/linebuffer_test/ip/linebuffer_test_auto_pc_0/linebuffer_test_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_auto_pc_0 || ORIG_REF_NAME==linebuffer_test_auto_pc_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_auto_ds_0/linebuffer_test_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_auto_ds_0 || ORIG_REF_NAME==linebuffer_test_auto_ds_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_auto_pc_1/linebuffer_test_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_auto_pc_1 || ORIG_REF_NAME==linebuffer_test_auto_pc_1}]

# IP: bd/linebuffer_test/ip/linebuffer_test_auto_us_0/linebuffer_test_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_auto_us_0 || ORIG_REF_NAME==linebuffer_test_auto_us_0}]

# IP: bd/linebuffer_test/ip/linebuffer_test_auto_ds_1/linebuffer_test_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_auto_ds_1 || ORIG_REF_NAME==linebuffer_test_auto_ds_1}]

# IP: bd/linebuffer_test/ip/linebuffer_test_auto_pc_2/linebuffer_test_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_auto_pc_2 || ORIG_REF_NAME==linebuffer_test_auto_pc_2}]

# IP: bd/linebuffer_test/ip/linebuffer_test_auto_us_1/linebuffer_test_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_auto_us_1 || ORIG_REF_NAME==linebuffer_test_auto_us_1}]

# XDC: bd/linebuffer_test/ip/linebuffer_test_processing_system7_0_0/linebuffer_test_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==linebuffer_test_processing_system7_0_0 || ORIG_REF_NAME==linebuffer_test_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/linebuffer_test/ip/linebuffer_test_rst_processing_system7_0_100M_0/linebuffer_test_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==linebuffer_test_rst_processing_system7_0_100M_0}]

# XDC: bd/linebuffer_test/ip/linebuffer_test_rst_processing_system7_0_100M_0/linebuffer_test_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linebuffer_test_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==linebuffer_test_rst_processing_system7_0_100M_0}]

# XDC: bd/linebuffer_test/ip/linebuffer_test_rst_processing_system7_0_100M_0/linebuffer_test_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_blk_mem_gen_0_1/linebuffer_test_blk_mem_gen_0_1_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_axi_bram_ctrl_0_1/linebuffer_test_axi_bram_ctrl_0_1_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_axi_cdma_0_1/linebuffer_test_axi_cdma_0_1_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_axi_cdma_0_1/linebuffer_test_axi_cdma_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==linebuffer_test_axi_cdma_0_1 || ORIG_REF_NAME==linebuffer_test_axi_cdma_0_1}] {/U0 }]/U0 ]]

# XDC: bd/linebuffer_test/ip/linebuffer_test_xbar_0/linebuffer_test_xbar_0_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_clk_wiz_0_0/linebuffer_test_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==linebuffer_test_clk_wiz_0_0 || ORIG_REF_NAME==linebuffer_test_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/linebuffer_test/ip/linebuffer_test_clk_wiz_0_0/linebuffer_test_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==linebuffer_test_clk_wiz_0_0 || ORIG_REF_NAME==linebuffer_test_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/linebuffer_test/ip/linebuffer_test_clk_wiz_0_0/linebuffer_test_clk_wiz_0_0_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_xbar_1/linebuffer_test_xbar_1_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_xbar_2/linebuffer_test_xbar_2_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_blk_mem_gen_0_0/linebuffer_test_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_axi_cdma_0_0/linebuffer_test_axi_cdma_0_0_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_axi_cdma_0_0/linebuffer_test_axi_cdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==linebuffer_test_axi_cdma_0_0 || ORIG_REF_NAME==linebuffer_test_axi_cdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/linebuffer_test/ip/linebuffer_test_axi_bram_ctrl_0_0/linebuffer_test_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_rgb2dvi_0_0/src/rgb2dvi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==linebuffer_test_rgb2dvi_0_0 || ORIG_REF_NAME==linebuffer_test_rgb2dvi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/linebuffer_test/ip/linebuffer_test_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==linebuffer_test_rgb2dvi_0_0 || ORIG_REF_NAME==linebuffer_test_rgb2dvi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/linebuffer_test/ip/linebuffer_test_clk_wiz_0_1/linebuffer_test_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==linebuffer_test_clk_wiz_0_1 || ORIG_REF_NAME==linebuffer_test_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/linebuffer_test/ip/linebuffer_test_clk_wiz_0_1/linebuffer_test_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==linebuffer_test_clk_wiz_0_1 || ORIG_REF_NAME==linebuffer_test_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/linebuffer_test/ip/linebuffer_test_clk_wiz_0_1/linebuffer_test_clk_wiz_0_1_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_auto_pc_0/linebuffer_test_auto_pc_0_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_auto_ds_0/linebuffer_test_auto_ds_0_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_auto_ds_0/linebuffer_test_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==linebuffer_test_auto_ds_0 || ORIG_REF_NAME==linebuffer_test_auto_ds_0}] {/inst }]/inst ]]

# XDC: bd/linebuffer_test/ip/linebuffer_test_auto_pc_1/linebuffer_test_auto_pc_1_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_auto_us_0/linebuffer_test_auto_us_0_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_auto_us_0/linebuffer_test_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==linebuffer_test_auto_us_0 || ORIG_REF_NAME==linebuffer_test_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/linebuffer_test/ip/linebuffer_test_auto_ds_1/linebuffer_test_auto_ds_1_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_auto_ds_1/linebuffer_test_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==linebuffer_test_auto_ds_1 || ORIG_REF_NAME==linebuffer_test_auto_ds_1}] {/inst }]/inst ]]

# XDC: bd/linebuffer_test/ip/linebuffer_test_auto_pc_2/linebuffer_test_auto_pc_2_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_auto_us_1/linebuffer_test_auto_us_1_ooc.xdc

# XDC: bd/linebuffer_test/ip/linebuffer_test_auto_us_1/linebuffer_test_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==linebuffer_test_auto_us_1 || ORIG_REF_NAME==linebuffer_test_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/linebuffer_test/linebuffer_test_ooc.xdc
