# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/ZYBO_Master.xdc

# XDC: new/debug.xdc

# Block Designs: bd/zybo_receiver/zybo_receiver.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver || ORIG_REF_NAME==zybo_receiver}]

# IP: bd/zybo_receiver/ip/zybo_receiver_processing_system7_0_0/zybo_receiver_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_processing_system7_0_0 || ORIG_REF_NAME==zybo_receiver_processing_system7_0_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_dvi2rgb_0_0/zybo_receiver_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_dvi2rgb_0_0 || ORIG_REF_NAME==zybo_receiver_dvi2rgb_0_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_clk_wiz_0_0/zybo_receiver_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_clk_wiz_0_0 || ORIG_REF_NAME==zybo_receiver_clk_wiz_0_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_i_buf_controller_0_0/zybo_receiver_i_buf_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_i_buf_controller_0_0 || ORIG_REF_NAME==zybo_receiver_i_buf_controller_0_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_xlconstant_0_0/zybo_receiver_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_xlconstant_0_0 || ORIG_REF_NAME==zybo_receiver_xlconstant_0_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_xlslice_0_0/zybo_receiver_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_xlslice_0_0 || ORIG_REF_NAME==zybo_receiver_xlslice_0_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_blk_mem_gen_0_0/zybo_receiver_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_blk_mem_gen_0_0 || ORIG_REF_NAME==zybo_receiver_blk_mem_gen_0_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_xlconstant_0_1/zybo_receiver_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_xlconstant_0_1 || ORIG_REF_NAME==zybo_receiver_xlconstant_0_1}]

# IP: bd/zybo_receiver/ip/zybo_receiver_xlconcat_0_0/zybo_receiver_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_xlconcat_0_0 || ORIG_REF_NAME==zybo_receiver_xlconcat_0_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_axi_bram_ctrl_0_0/zybo_receiver_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_axi_bram_ctrl_0_0 || ORIG_REF_NAME==zybo_receiver_axi_bram_ctrl_0_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_axi_cdma_0_0/zybo_receiver_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_axi_cdma_0_0 || ORIG_REF_NAME==zybo_receiver_axi_cdma_0_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_axi_mem_intercon_0/zybo_receiver_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_axi_mem_intercon_0 || ORIG_REF_NAME==zybo_receiver_axi_mem_intercon_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_rst_processing_system7_0_100M_0/zybo_receiver_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zybo_receiver_rst_processing_system7_0_100M_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_xbar_0/zybo_receiver_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_xbar_0 || ORIG_REF_NAME==zybo_receiver_xbar_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_processing_system7_0_axi_periph_0/zybo_receiver_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==zybo_receiver_processing_system7_0_axi_periph_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_rgb2vga_0_0/zybo_receiver_rgb2vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_rgb2vga_0_0 || ORIG_REF_NAME==zybo_receiver_rgb2vga_0_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_o_buf_controller_0_0/zybo_receiver_o_buf_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_o_buf_controller_0_0 || ORIG_REF_NAME==zybo_receiver_o_buf_controller_0_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_xlconcat_0_1/zybo_receiver_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_xlconcat_0_1 || ORIG_REF_NAME==zybo_receiver_xlconcat_0_1}]

# IP: bd/zybo_receiver/ip/zybo_receiver_blk_mem_gen_0_1/zybo_receiver_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_blk_mem_gen_0_1 || ORIG_REF_NAME==zybo_receiver_blk_mem_gen_0_1}]

# IP: bd/zybo_receiver/ip/zybo_receiver_axi_bram_ctrl_0_1/zybo_receiver_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_axi_bram_ctrl_0_1 || ORIG_REF_NAME==zybo_receiver_axi_bram_ctrl_0_1}]

# IP: bd/zybo_receiver/ip/zybo_receiver_axi_cdma_0_1/zybo_receiver_axi_cdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_axi_cdma_0_1 || ORIG_REF_NAME==zybo_receiver_axi_cdma_0_1}]

# IP: bd/zybo_receiver/ip/zybo_receiver_axi_mem_intercon_1_0/zybo_receiver_axi_mem_intercon_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_axi_mem_intercon_1_0 || ORIG_REF_NAME==zybo_receiver_axi_mem_intercon_1_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_xbar_1/zybo_receiver_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_xbar_1 || ORIG_REF_NAME==zybo_receiver_xbar_1}]

# IP: bd/zybo_receiver/ip/zybo_receiver_xbar_2/zybo_receiver_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_xbar_2 || ORIG_REF_NAME==zybo_receiver_xbar_2}]

# IP: bd/zybo_receiver/ip/zybo_receiver_xlconcat_0_2/zybo_receiver_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_xlconcat_0_2 || ORIG_REF_NAME==zybo_receiver_xlconcat_0_2}]

# IP: bd/zybo_receiver/ip/zybo_receiver_auto_pc_0/zybo_receiver_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_auto_pc_0 || ORIG_REF_NAME==zybo_receiver_auto_pc_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_auto_ds_0/zybo_receiver_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_auto_ds_0 || ORIG_REF_NAME==zybo_receiver_auto_ds_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_auto_us_0/zybo_receiver_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_auto_us_0 || ORIG_REF_NAME==zybo_receiver_auto_us_0}]

# IP: bd/zybo_receiver/ip/zybo_receiver_auto_pc_1/zybo_receiver_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_auto_pc_1 || ORIG_REF_NAME==zybo_receiver_auto_pc_1}]

# IP: bd/zybo_receiver/ip/zybo_receiver_auto_pc_2/zybo_receiver_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_auto_pc_2 || ORIG_REF_NAME==zybo_receiver_auto_pc_2}]

# IP: bd/zybo_receiver/ip/zybo_receiver_auto_ds_1/zybo_receiver_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_auto_ds_1 || ORIG_REF_NAME==zybo_receiver_auto_ds_1}]

# IP: bd/zybo_receiver/ip/zybo_receiver_auto_us_1/zybo_receiver_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_auto_us_1 || ORIG_REF_NAME==zybo_receiver_auto_us_1}]

# XDC: bd/zybo_receiver/ip/zybo_receiver_processing_system7_0_0/zybo_receiver_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_receiver_processing_system7_0_0 || ORIG_REF_NAME==zybo_receiver_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/zybo_receiver/ip/zybo_receiver_dvi2rgb_0_0/src/dvi2rgb.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_receiver_dvi2rgb_0_0 || ORIG_REF_NAME==zybo_receiver_dvi2rgb_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zybo_receiver/ip/zybo_receiver_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_clk_wiz_0_0/zybo_receiver_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_receiver_clk_wiz_0_0 || ORIG_REF_NAME==zybo_receiver_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/zybo_receiver/ip/zybo_receiver_clk_wiz_0_0/zybo_receiver_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_receiver_clk_wiz_0_0 || ORIG_REF_NAME==zybo_receiver_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/zybo_receiver/ip/zybo_receiver_clk_wiz_0_0/zybo_receiver_clk_wiz_0_0_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_blk_mem_gen_0_0/zybo_receiver_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_axi_bram_ctrl_0_0/zybo_receiver_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_axi_cdma_0_0/zybo_receiver_axi_cdma_0_0_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_axi_cdma_0_0/zybo_receiver_axi_cdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_receiver_axi_cdma_0_0 || ORIG_REF_NAME==zybo_receiver_axi_cdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zybo_receiver/ip/zybo_receiver_rst_processing_system7_0_100M_0/zybo_receiver_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zybo_receiver_rst_processing_system7_0_100M_0}]

# XDC: bd/zybo_receiver/ip/zybo_receiver_rst_processing_system7_0_100M_0/zybo_receiver_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_receiver_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zybo_receiver_rst_processing_system7_0_100M_0}]

# XDC: bd/zybo_receiver/ip/zybo_receiver_rst_processing_system7_0_100M_0/zybo_receiver_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_xbar_0/zybo_receiver_xbar_0_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_blk_mem_gen_0_1/zybo_receiver_blk_mem_gen_0_1_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_axi_bram_ctrl_0_1/zybo_receiver_axi_bram_ctrl_0_1_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_axi_cdma_0_1/zybo_receiver_axi_cdma_0_1_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_axi_cdma_0_1/zybo_receiver_axi_cdma_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_receiver_axi_cdma_0_1 || ORIG_REF_NAME==zybo_receiver_axi_cdma_0_1}] {/U0 }]/U0 ]]

# XDC: bd/zybo_receiver/ip/zybo_receiver_xbar_1/zybo_receiver_xbar_1_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_xbar_2/zybo_receiver_xbar_2_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_auto_pc_0/zybo_receiver_auto_pc_0_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_auto_ds_0/zybo_receiver_auto_ds_0_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_auto_ds_0/zybo_receiver_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_receiver_auto_ds_0 || ORIG_REF_NAME==zybo_receiver_auto_ds_0}] {/inst }]/inst ]]

# XDC: bd/zybo_receiver/ip/zybo_receiver_auto_us_0/zybo_receiver_auto_us_0_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_auto_us_0/zybo_receiver_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_receiver_auto_us_0 || ORIG_REF_NAME==zybo_receiver_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/zybo_receiver/ip/zybo_receiver_auto_pc_1/zybo_receiver_auto_pc_1_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_auto_pc_2/zybo_receiver_auto_pc_2_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_auto_ds_1/zybo_receiver_auto_ds_1_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_auto_ds_1/zybo_receiver_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_receiver_auto_ds_1 || ORIG_REF_NAME==zybo_receiver_auto_ds_1}] {/inst }]/inst ]]

# XDC: bd/zybo_receiver/ip/zybo_receiver_auto_us_1/zybo_receiver_auto_us_1_ooc.xdc

# XDC: bd/zybo_receiver/ip/zybo_receiver_auto_us_1/zybo_receiver_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_receiver_auto_us_1 || ORIG_REF_NAME==zybo_receiver_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/zybo_receiver/zybo_receiver_ooc.xdc
