webtalk_init -webtalk_dir /home/mike/Documents/osiris-hdl/projects/zybo_dvi_input/zybo_dvi_input.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Feb 13 22:06:42 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211128440_1777513797_210620123_049" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "72cd5575-16a9-4e81-9b32-c068749277c6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6721384c-e4e4-4bed-ad6b-2b0ace420a3d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "elementary OS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "elementary OS Freya" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU           X5667  @ 3.07GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1596.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_transmit -clientid 3570903072 -regid "211128440_1777513797_210620123_049" -xml /home/mike/Documents/osiris-hdl/projects/zybo_dvi_input/zybo_dvi_input.hw/webtalk/usage_statistics_ext_labtool.xml -html /home/mike/Documents/osiris-hdl/projects/zybo_dvi_input/zybo_dvi_input.hw/webtalk/usage_statistics_ext_labtool.html -wdm /home/mike/Documents/osiris-hdl/projects/zybo_dvi_input/zybo_dvi_input.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
